# Generated by Django 4.2.23 on 2025-07-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField(help_text='YouTube/Blog/Website URL')),
                ('category', models.CharField(choices=[('youtube', 'YouTube Playlist'), ('blog', 'Blog Article'), ('website', 'Learning Website'), ('pdf', 'PDF/Notes'), ('other', 'Other')], max_length=50)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Learning Resource',
                'verbose_name_plural': 'Learning Resources',
                'ordering': ['-date_added'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_created'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(verbose_name='GitHub Repository'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, null=True, verbose_name='Live Demo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', to='portfolio.technology'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Programming Language'), ('framework', 'Framework'), ('frontend', 'Frontend Technologies'), ('backend', 'Backend & Databases'), ('tool', 'Tools & Platforms'), ('other', 'Other Skills')], max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
